eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: config-client
  zipkin: 
    base-url: http://localhost:9411
  cloud:
    config:
      label: master
      profile: dev
#     uri: http://localhost:8888/
      discovery:
        enabled: true
        serviceId : config-server

#开启 feigin断路器
feign:
  hystrix:
    enabled: true